larger_capital_cities = [
    "Tokyo",
    "Delhi",
    "Beijing",
    "Moscow",
    "Dhaka",
    "Cairo",
    "London",
    "Bangkok",
    "Tehran",
    "Riyadh",
    "Istanbul",
    "Lahore",
    "Shanghai",
    "Karachi",
    "Paris",
    "Lima",
    "Mexico City",
    "Kinshasa",
    "Lagos",
    "Cape Town",
    "Nairobi",
    "Buenos Aires",
    "Toronto",
    "Sydney",
    "Berlin",
    "Jakarta",
    "Manila",
    "New Delhi",
    "Seoul",
    "Hanoi",
    "Oslo",
    "Budapest",
    "Amman",
    "Montevideo",
    "Warsaw",
    "Vienna",
    "Kiev",
    "Helsinki",
    "Stockholm",
    "Athens",
    "Copenhagen",
    "Dublin",
    "Lisbon",
    "Madrid",
    "Amsterdam",
    "Brussels",
    "Prague",
    "Brasília",
    "Copenhagen",
    ]